export const users = [
  {
    _id: "675459da2e8ff0b361496070",
    name: "Mayuresh Gawas",
    email: "narayan.gawas@spit.ac.in",
    password: "$2a$10$zNKiQuH6ZZWnWcxg9YVgX.8V5DVW4dykLfjfRaKjgE0YbLGlcjsWG",
    skills: ["Python", "Java"],
    pic: "https://res.cloudinary.com/djuseai07/image/upload/v1700404138/jappmsksbbpviexsfdic.jpg",
    __v: 31,
    about:
      "I'm Narayan (Mayuresh) Gawas, a dedicated B.Tech student majoring in Electronics and Telecommunications at Sardar Patel Institute of Technology. With a consistent academic record and a first-place rank in my second year, I've demonstrated my commitment to excellence in my studies. My education journey also includes a Diploma in Electronics from Veermata Jijabai Technological Institute, where I secured the 6th rank, and high school achievements at Dr. Bedekar Vidya Mandir, where I placed 3rd.\n\nI'm passionate about web development and have hands-on experience with projects like \"iNotebook\" and an e-commerce website. My coding prowess shines through my 4-star Codechef rating, 500+ problem solves on GeeksforGeeks, and a 5-star Hackerrank rating in Python. I'm particularly proud of my 3rd institute rank on GeeksforGeeks, 8th institute rank on Codechef, and my consistent drive for excellence. Proficient in Python, JavaScript, SQL, HTML, CSS, React, Redux, Express, and Bootstrap, I'm eager to apply my skills and knowledge to real-world challenges and projects.",
    organization: "SPIT",
    headline:
      "Graduate Analyst at Deutsche Bank | ICPC Regionalist '23 | Full Stack Developer | 4★ @codechef | Minecrafter⛏️",
    connections: ["6762bc2d02666ca16a85b120"],
    isAdmin: false,
  },
  {
    _id: "676fb08ed5eda9140e898bb7",
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    password: "$2a$10$nU9ay.vfOX8tDwHBgkNvEOGt9CEKx762c2Avmk.ajwzRXA1eW2ftS",
    isAdmin: false,
    skills: [],
    pic: "https://icon-library.com/images/anonymous-avatar-icon/anonymous-avatar-icon-25.jpg",
    __v: 0,
  },
  {
    _id: "676fb08ed5eda9140e898bb8",
    name: "Bob Smith",
    email: "bob.smith@example.com",
    password: "$2a$10$nU9ay.vfOX8tDwHBgkNvEOGt9CEKx762c2Avmk.ajwzRXA1eW2ftS",
    isAdmin: false,
    skills: [],
    pic: "https://icon-library.com/images/anonymous-avatar-icon/anonymous-avatar-icon-25.jpg",
    __v: 0,
  },
  {
    _id: "676fb08ed5eda9140e898bb9",
    name: "Charlie Brown",
    email: "charlie.brown@example.com",
    password: "$2a$10$nU9ay.vfOX8tDwHBgkNvEOGt9CEKx762c2Avmk.ajwzRXA1eW2ftS",
    isAdmin: false,
    skills: [],
    pic: "https://icon-library.com/images/anonymous-avatar-icon/anonymous-avatar-icon-25.jpg",
    __v: 0,
  },
  {
    _id: "676fb08ed5eda9140e898bba",
    name: "Diana Ross",
    email: "diana.ross@example.com",
    password: "$2a$10$nU9ay.vfOX8tDwHBgkNvEOGt9CEKx762c2Avmk.ajwzRXA1eW2ftS",
    isAdmin: false,
    skills: [],
    pic: "https://icon-library.com/images/anonymous-avatar-icon/anonymous-avatar-icon-25.jpg",
    __v: 0,
  },
  {
    _id: "676fb08ed5eda9140e898bb7",
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    password: "$2a$10$nU9ay.vfOX8tDwHBgkNvEOGt9CEKx762c2Avmk.ajwzRXA1eW2ftS",
    isAdmin: false,
    skills: [],
    pic: "https://icon-library.com/images/anonymous-avatar-icon/anonymous-avatar-icon-25.jpg",
    __v: 0,
  },
  {
    _id: "676fb08ed5eda9140e898bb8",
    name: "Bob Smith",
    email: "bob.smith@example.com",
    password: "$2a$10$nU9ay.vfOX8tDwHBgkNvEOGt9CEKx762c2Avmk.ajwzRXA1eW2ftS",
    isAdmin: false,
    skills: [],
    pic: "https://icon-library.com/images/anonymous-avatar-icon/anonymous-avatar-icon-25.jpg",
    __v: 0,
  },
  {
    _id: "676fb08ed5eda9140e898bb9",
    name: "Charlie Brown",
    email: "charlie.brown@example.com",
    password: "$2a$10$nU9ay.vfOX8tDwHBgkNvEOGt9CEKx762c2Avmk.ajwzRXA1eW2ftS",
    isAdmin: false,
    skills: [],
    pic: "https://icon-library.com/images/anonymous-avatar-icon/anonymous-avatar-icon-25.jpg",
    __v: 0,
  },
  {
    _id: "676fb08ed5eda9140e898bba",
    name: "Diana Ross",
    email: "diana.ross@example.com",
    password: "$2a$10$nU9ay.vfOX8tDwHBgkNvEOGt9CEKx762c2Avmk.ajwzRXA1eW2ftS",
    isAdmin: false,
    skills: [],
    pic: "https://icon-library.com/images/anonymous-avatar-icon/anonymous-avatar-icon-25.jpg",
    __v: 0,
  },
];
